### ISSUE TITLE
remote debugging (windows -> linux)

### ISSUE THREAD

**Issue by ezverev** [mono/debugger-libs#188]
Hello everybody.

My issue is more a question at the moment. 
I dove into the task of remote debugging a mono app running on a Linux machine and I am limited to windows and visual studio in terms of IDE.
I do understand that this scenario is not supported by the mono team. But I managed to reanimate the VS extension and successfully got into debugging but I have issues with the Mono.Debugging.Soft.SoftDebuggerSession and in particular how it accesses the file system.

So my question is: do the debugger-libs welcome pull requests targeted on enhancing support for remote debugging at all?

**Comment by joj** [comment]
@ezverev this may be helpful in your scenario: https://github.com/xamarin/vs-mono-debugger-sample. The sample is slightly outdated, but it's debugging a mono windows app on windows and you don't have to go through all the process of adapting debugger libs for vs (because I did already :) ). Adapting to Linux will only imply forwarding the debugger port and adding a proper "run" procedure. Based on your comment you may already be using that, though.

**Comment by ezverev** [comment]
@joj Thanks, I was looking both at your code, https://github.com/Microsoft/vscode-mono-debug and https://github.com/kswoll/vs-mono while adopting the Mono.Debugger to visual studio. That is done.

Now I have problems with the Mono.Debugging.Soft itself. [SoftDebuggerSession](https://github.com/mono/debugger-libs/blob/a717546c9b1d10ee7fbe834f3c8e298fe9d2765a/Mono.Debugging.Soft/SoftDebuggerSession.cs#L2626) and [SoftDebuggerAdaptor ](https://github.com/mono/debugger-libs/blob/a717546c9b1d10ee7fbe834f3c8e298fe9d2765a/Mono.Debugging.Soft/SoftDebuggerAdaptor.cs#L613) classes have hardcoded file system access which implies that the file paths which come from the Mono.Debugger.Soft.VirtualMachine are local to the IDE running the debugger which is obviously false in my scenario.

**Comment by joj** [comment]
We use the same SDS and Adaptor for Android and iOS (which are also remote). The debugger included in VS* (and in the sample) is overriding SoftDebuggerStartInfo to specify paths to symbols. I'm not sure what paths you need to be remote instead of local, though. Paths to symbols is the only thing I can think of that we need local/remote, but I could be forgetting something.

*included in VS is actually included in Xamarin, but you'll be able to have it as a dependency in the next release, once it goes to stable.

**Comment by joj** [comment]
I don't want to be misleading: you are more than welcome to send a PR if you want. I just think it's very likely that your scenario is already covered and it may be easier for you if it is.

**Comment by ezverev** [comment]
Did I get you right that the <package id="Mono.Debugging.VisualStudio" version="4.9.3-pre" targetFramework="net452" /> package is not forsaken and is going to be released? I failed to find its source code and thought it's not on the table anymore.

Does it go on but just not public?

As for the paths (local/remote): it's not just symbols. Binary paths are being used for analysis via Cecil/Roslyn as well: [example](https://github.com/mono/debugger-libs/blob/a717546c9b1d10ee7fbe834f3c8e298fe9d2765a/Mono.Debugging.Soft/SoftDebuggerSession.cs#L2632).

**Comment by joj** [comment]
The vs debugger will not be made public but it will be made a system component in the installer, meaning that if you add a Depends on it in your vsix, it will be found and installed automatically. Right now it is only installed when installing Xamarin.

 In Android and iOS we use the dlls/pdbs in your bin folder for debugging, not the ones in the device because they are identical anyway and it's way faster to load locally than to be remoting everything all the time. The debugger in the sample is the same we use for Android and iOS.

**Comment by ezverev** [comment]
@joj Hi there!
I am asking for an advice, a hint.
I gave it a shot with the https://github.com/xamarin/vs-mono-debugger-sample of yours and got stuck with the breakpoints ignored by visual studio. I must be doing something totally wrong here.

I run the mono program execution on my Linux machine with the following command via SSH:
DISPLAY=<VS_station_IP>:0 XAUTHORITY=/var/run/lightdm/user/xauthority mono --debug=mdb-optimizations --debugger-agent=transport=dt_socket,address=0.0.0.0:6438,server=y /home/user/run_test/MonoProgram1.exe
The mono starts and awaits for the connection from IDE.

Then I launch the Visual Studio with a slightly modified Mono.Debugger.Sample:
1. Instead of SoftDebuggerListenArgs I create the SoftDebuggerConnectArgs:
`var startArgs = new SoftDebuggerConnectArgs("MonoProgram1", IPAddress.Parse("10.0.140.162"), 6438);`
2. In MonoSampleDebuggerSession.OnRun I commented out the System.Diagnostics.Process creation and launch.

After the IDE connects to the debug agent I start seeing the console output from my MonoProgram1.exe. 
When I set a breakpoint, MonoSampleDebuggerSession,OnInsertBreakEvent override does get called and I see correct source code path and line number.

But debugging does not stop on a breakpoint.
Would you be so kind as to guide me here please?

Thanks in advance.

**Comment by DavidKarlas** [comment]
Can you debug `OnInsertBreakEvent`? Also, is there Portable .pdb or .mdb next to `MonoProgram1.exe`?

**Comment by joj** [comment]
@ezverev what you're probably missing is reporting the symbols. That's part of the SoftDebuggerStartInfo (or StartInfo, from the Mono.Debugging.VisualStudio.dll), and it's sent to VS when you use IDebugLauncher.StartDebugger. The relevant properties are AssemblyPathMap and UserAssemblyNames. If you're not setting those (you should be able to check somewhere on or after OnRun), then you will not get breakpoints or proper stack traces.

Also if you're using mdb I suggest you switch to portable. mdb is not getting updates and bug fixes. Portable works way better generally speaking.

**Comment by ezverev** [comment]
@DavidKarlas 

> Can you debug OnInsertBreakEvent?
I am trying to do it now. The problem is the **Mono.Debugger.Soft** sources are ported into vs2017 syntax and cannot be attached to the project directly. It took me the whole day today trying to port the **Mono.Debugger.Sample** to vs2017. I will try to finish that to be able to debug **OnInsertBreakEvent**.

> Also, is there Portable .pdb or .mdb next to MonoProgram1.exe?
I am using .pdb (the target mono app is built with MSBuild, not XBuid).

@joj Thank you for the advice, I will try to check that.

**Comment by DavidKarlas** [comment]
Did you build it on linux or windows? If you are compiling on Windows, change `<DebugType>full</DebugType>` to `<DebugType>portable</DebugType>` in your `MonoProgram1.csproj`.

**Comment by ezverev** [comment]
@DavidKarlas Thank you for the advice, I will try that. I was building on Windows with `<DebugType>full</DebugType>`.
