### ISSUE TITLE
MDB Files for Runtime Compiled Code

### ISSUE THREAD

**Issue by aluitink** [mono/debugger-libs#72]
Hi, I'm wondering about the debug-ability of code that is compiled at runtime. There is a CSharpCodeProvider that allows you to compile a file from within another application at runtime and load those modules into memory for execution.

I think there would be a few logistical issues, but let's pretend that I'm able to generate a PDB and MDB file, do these files need to be present before the application is executed?

I'm playing around with Microsoft's DNX bootstrap, which appears to build a DNX project at runtime and execute it. I've pre generated the PDB and converted to an MDB but can't get the debug agent to load it.

If I build the application and execute it directly with the MDB file, I seem to receive proper debug info on the remote end.

Could anyone explain the process the debug agent follows for loading MDB files (I'm assuming this is my downfall).

Would there be a way to extend the debug agent to allow me to sideload an MDB file on the fly?

I'm kind of just brain storming at the moment, but any info would be appreciated.

**Comment by DavidKarlas** [comment]
I guess we must 1st clarify what runtime we are targeting.. I assume it's Mono runtime...

I added support for debugging DNX projects via XS DNX AddIn here: https://github.com/mrward/monodevelop-dnx-addin/pull/4/files#diff-31096e0d1ee3a4b59df0056e438c8307R48 key thing was environment variable DNX_BUILD_PORTABLE_PDB set to 1(because thats what Roslyn supports on non-Windows)...

Basically the trick is that when CSharpCodeProvider or w/e method you use to produce .dll and debug symbol(.mdb or portable .pdb is supported(if you have classic .pdb you will need to do pdb2mdb(you can find source code(few files) in mono repro instead of pdb2mdb.exe)) is to load it via Assembly.Load(byte[], byte[]) where 2nd byte[] argument is .mdb(or porable .pdb bytes): https://msdn.microsoft.com/en-us/library/twt16z2x(v=vs.110).aspx

This is what DNX does somewhere inside when it compiles portable .pdb via Roslyn if that environment variable is set...

**Comment by DavidKarlas** [comment]
Let me note that with .NET API it's a bit harder since IDE also needs access to .pdb file, while on Mono all debug symbols processing is done by runtime...(there is one exception but lets ignore it for now)
